package(default_visibility = ["PUBLIC"])

proto_library(
    name = "finance",
    srcs = ["finance.proto"],
    languages = ["go"]
)

proto_library(
    name = "examples",
    srcs = ["examples.proto"],
    languages = ["go"]
)
