subinclude("//tools:proto_decoder")

proto_decoder(
    name = "simple_message_decoder",
    args = [],
    proto_target = "//proto:examples",
    message = "SimpleMessage",
    visibility = [
        "//tests/..."
    ],
)
