package(default_visibility = ["PUBLIC"])

filegroup(
    name = "proto_decoder",
    srcs = ["proto_decoder.build_defs"],
)

filegroup(
    name = "proto_encoder",
    srcs = ["proto_encoder.build_defs"],
)
